chipset = "Advanced Micro Devices, Inc. [AMD] Phoenix Root Complex"
cpu_model = "AMD Ryzen 5 8500GE w/ Radeon 740M Graphics"
degraded = true
hash_components = [
  "cpu_model",
  "cpu_base_mhz",
  "mem_speed_mts",
  "mem_timings",
  "board",
  "chipset",
]
hash_observed = ["cpu_model", "mem_speed_mts", "board", "chipset"]

[board]
name = "334A"
vendor = "LENOVO"

[mem]
parts = ["M425R2GA3EB0-CWMOL"]
speed_mts = 5200
total_bytes = 15849508864
