chipset = "Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Root Complex"
cpu_model = "AMD Ryzen 9 9950X 16-Core Processor"
degraded = true
hash_components = [
    "cpu_model",
    "cpu_base_mhz",
    "mem_speed_mts",
    "mem_timings",
    "board",
    "chipset",
]
hash_observed = [
    "cpu_model",
    "mem_speed_mts",
    "board",
    "chipset",
]

[board]
name = "X870E Taichi Lite"
vendor = "ASRock"

[mem]
parts = []
speed_mts = 6000
